{
 "title": "Message of the day",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Count Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_count_total" }
   ]
  },
  {
   "title": "/info Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_latency_seconds_sum{endpoint=~\"/info\"}"
    }
   ]
  },
  {
   "title": "/info total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_count_total{endpoint=~\"/info\"}"
    }
   ]
  },
  {
   "title": "Latency count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_latency_seconds_count" }
   ]
  }
 ]
}