---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: msg-of-the-day
  name: msg-of-the-day-svc
spec:
  ports:
    - name: http-port-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: msg-of-the-day
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-of-the-day
spec:
  selector:
    matchLabels:
      app: msg-of-the-day
  replicas: 1
  template:
    metadata:
      labels:
        app: msg-of-the-day
    spec:
      containers:
      - name: "c7-msg-of-the-day"
        image: gcr.io/test-ke-246205/c7-msg-of-the-day:latest
        volumeMounts:
          - name: local-vol
            mountPath: /sys/fs/cgroup
        securityContext:
          privileged: true
        ports:
        - containerPort: 5000
      volumes:
        - name: local-vol
          hostPath:
            path: /sys/fs/cgroup
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: msg-of-the-day
  name: msg-of-the-day-ingress
spec:
  backend:
    serviceName: msg-of-the-day-svc
    servicePort: http-port-5000